version: "3.8"

networks:
    leogantt-net:
        driver: bridge

volumes:
    leogantt-volume:
    
services:
    database:
        image: mysql/mysql-server
        ports: 
            - 33061:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wearejustpros
            MYSQL_DATABASE: just
            MYSQL_USER: root
            MYSQL_PASSWORD: wearejustpros
        volumes:
            - leogantt-volume:/home/volumes
        networks:
            - leogantt-net
        container_name: leogantt-database
    
    backend:
        build: ../Backend
        ports:
            - 8080:80
        environment:
            ConnectionStrings__DefaultConnection: "Server=localhost;Port=33061;Database=just;User=root;Password=wearejustpros"
        networks:
            - leogantt-net
        container_name: leogantt-backend
        
    frontend:
        build: ../Frontend/just-reworked
        ports:
            - 4201:80
        networks:
            - leogantt-net
        container_name: leogantt-frontend