version: "3.8"

networks:
    just-net:
        driver: bridge

volumes:
    just-volume:
    
services:
    database:
        image: mysql/mysql-server
        ports: 
            - 33061:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wearejustpros
            MYSQL_DATABASE: just
            MYSQL_USER: root
            MYSQL_PASSWORD: wearejustpros
        volumes:
            - just-volume:/home/volumes
        networks:
            - just-net

    